version: '3.8'

services:
  app:
    image: mamaligalover/cmv:latest # Folosește imaginea de pe Docker Hub
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/app/uploads # Salvare fișiere pe diskul local
    environment:
      - UPLOADS_PATH=/app/uploads
      - ConnectionStrings__DefaultConnection=Server=db;Database=CMVMD;User Id=postgres;Password=postgres;
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: CMVMD
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: